[package]
name = "task"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-utils = "0.1.0"

[dev-dependencies]
futures-lite = "2.0.0"
async-executor = "1.5.0"
async-task = "4.3.0"
